import { NextRequest } from 'next/server';
import { randomUUID } from 'crypto';
import { putPrivate, readPrivate, deletePrivate } from '../../../lib/blob';
import { db, ensureSchema } from '../../../lib/db';
import { getUser, csrfToken } from '../../../lib/auth';
import * as decart from '../../../lib/decart';

export const runtime = 'nodejs';
export const maxDuration = 800;
const LIMITS={max_image_bytes:5*1024*1024,max_video_bytes:150*1024*1024,allowed_images:['image/jpeg','image/png','image/webp'],allowed_videos:['video/mp4','video/webm','video/quicktime']};
const now=()=>new Date().toISOString();
function json(data:any,status=200){return Response.json(data,{status});}
function formValue(fd:FormData,k:string){return String(fd.get(k)||'');}
async function guard(req:NextRequest){ const token=req.headers.get('x-csrf-token'); const expected=await csrfToken(); if(req.method!=='GET' && (!token || token!==expected)) throw new Error('Security check failed. Refresh the page and try again.'); }
async function asset(userId:number,id:number){const s=db(); const rows=await s`SELECT * FROM assets WHERE id=${id} AND user_id=${userId}`; if(!rows.length) throw new Error('Asset not found'); return rows[0];}
async function projectOk(userId:number,id:number){if(!id)return null; const s=db(); const rows=await s`SELECT id FROM projects WHERE id=${id} AND user_id=${userId}`; return rows.length?Number(rows[0].id):null;}
async function notify(userId:number,type:string,title:string,message:string,generationId?:number){await db()`INSERT INTO notifications(user_id,type,title,message,generation_id,created_at) VALUES(${userId},${type},${title},${message},${generationId||null},${now()})`;}
function assetOut(r:any){return {...r,id:Number(r.id),user_id:r.user_id?Number(r.user_id):null,project_id:r.project_id?Number(r.project_id):null,size_bytes:Number(r.size_bytes),url:`/api/asset/${r.id}`};}
function genOut(r:any){const out=(r as any).output;return {...r,id:Number(r.id),user_id:r.user_id?Number(r.user_id):null,project_id:r.project_id?Number(r.project_id):null,output_asset_id:r.output_asset_id?Number(r.output_asset_id):null,input_asset_ids:typeof r.input_asset_ids==='string'?r.input_asset_ids:JSON.stringify(r.input_asset_ids||[]),metadata_json:typeof r.metadata_json==='string'?r.metadata_json:JSON.stringify(r.metadata_json||{}),output:out};}

export async function GET(req:NextRequest,{params}:{params:Promise<{route:string}>}){try{await ensureSchema();await guard(req);const {route}=await params;const user=await getUser();const s=db();
 if(route==='config'){const rows=await s`SELECT workspace,model_id,endpoint_kind,enabled FROM model_config`;const models:any={};for(const r of rows)models[r.workspace]=r;return json({app:'ANONYMOUX STUDIO',models,limits:LIMITS,csrf:await csrfToken()});}
 if(route==='dashboard'){const recent=await s`SELECT id,workspace,status,prompt,project_id,created_at,output_asset_id FROM generations WHERE user_id=${user.id} ORDER BY created_at DESC LIMIT 8`;const out:any[]=[];for(const r of recent){let output=null;if(r.output_asset_id){const a=await asset(user.id,Number(r.output_asset_id));output=assetOut(a)}out.push({...r,id:Number(r.id),project_id:r.project_id?Number(r.project_id):null,output});}const counts=await s`SELECT status,count(*)::int c FROM generations WHERE user_id=${user.id} GROUP BY status`;const c:any={};for(const r of counts)c[r.status]=r.c;const [ac]=await s`SELECT count(*)::int c FROM assets WHERE user_id=${user.id}`;const [pc]=await s`SELECT count(*)::int c FROM projects WHERE user_id=${user.id}`;return json({recent:out,counts:c,asset_count:ac.c,project_count:pc.c,workspace_count:5});}
 if(route==='projects'){const rows=await s`SELECT p.*, (SELECT count(*)::int FROM generations g WHERE g.project_id=p.id AND g.user_id=p.user_id) generation_count, (SELECT count(*)::int FROM assets a WHERE a.project_id=p.id AND a.user_id=p.user_id) asset_count FROM projects p WHERE p.user_id=${user.id} ORDER BY p.updated_at DESC`;return json({items:rows.map((r:any)=>({...r,id:Number(r.id),user_id:r.user_id?Number(r.user_id):null}))});}
 if(route==='history'){const rows=await s`SELECT * FROM generations WHERE user_id=${user.id} ORDER BY created_at DESC LIMIT 200`;const items:any[]=[];for(const r of rows){let output=null;if(r.output_asset_id){const a=await asset(user.id,Number(r.output_asset_id));output=assetOut(a)}items.push({...genOut(r),inputs:r.input_asset_ids||[],output});}return json({items});}
 if(route==='generation-status'){const id=Number(req.nextUrl.searchParams.get('id'));const rows=await s`SELECT * FROM generations WHERE id=${id} AND user_id=${user.id}`;if(!rows.length)throw new Error('Generation not found');let g=rows[0];if(g.provider_job_id && !['completed','failed'].includes(String(g.status))){const job=await decart.getJob(String(g.provider_job_id));const status=String(job.status||'processing');const raw=job.progress??job.percent;const progress=typeof raw==='number'?Math.max(0,Math.min(100,raw)):status==='completed'?100:25;if(['completed','failed','cancelled'].includes(status)){if(status==='completed'){const rr=await decart.getContent(String(g.provider_job_id));const ct=rr.headers.get('content-type')||'video/mp4';const ext=ct.includes('webm')?'webm':'mp4';const pathname=`generated/${new Date().toISOString().slice(0,7).replace('-','/')}/${randomUUID()}.${ext}`;const blob=await putPrivate(pathname,await rr.blob(),ct);const size=Number(rr.headers.get('content-length')||0);const ins=await s`INSERT INTO assets(user_id,project_id,kind,original_name,path,mime,size_bytes,source,created_at) VALUES(${user.id},${g.project_id},'generated',${`generated-${id}.${ext}`},${pathname},${ct},${size},'generated',${now()}) RETURNING *`;const outId=Number(ins[0].id);await s`UPDATE generations SET status='completed',output_asset_id=${outId},metadata_json=${JSON.stringify(job)}::jsonb,completed_at=${now()} WHERE id=${id}`;await notify(user.id,'success','Generation completed',`Your ${g.workspace} result is ready.`,id);g=(await s`SELECT * FROM generations WHERE id=${id}`)[0];(g as any).output=assetOut(ins[0]);}else{const msg=String(job.error||job.message||'Decart generation failed');await s`UPDATE generations SET status='failed',error_message=${msg},metadata_json=${JSON.stringify(job)}::jsonb,completed_at=${now()} WHERE id=${id}`;await notify(user.id,'error','Generation failed',msg,id);g=(await s`SELECT * FROM generations WHERE id=${id}`)[0];}}
 else {await s`UPDATE generations SET metadata_json=${JSON.stringify({...job,progress})}::jsonb WHERE id=${id}`;g=(await s`SELECT * FROM generations WHERE id=${id}`)[0];}}
 if(!(g as any).output && g.output_asset_id){const a=await asset(user.id,Number(g.output_asset_id));(g as any).output=assetOut(a);}return json({generation:genOut(g)});}
 if(route==='assets'){const rows=await s`SELECT * FROM assets WHERE user_id=${user.id} ORDER BY created_at DESC LIMIT 500`;return json({items:rows.map(assetOut)});}
 if(route==='prompts'){const rows=await s`SELECT * FROM prompts WHERE user_id=${user.id} ORDER BY updated_at DESC`;return json({items:rows.map((r:any)=>({...r,id:Number(r.id),user_id:r.user_id?Number(r.user_id):null}))});}
 if(route==='notifications'){const rows=await s`SELECT * FROM notifications WHERE user_id=${user.id} ORDER BY created_at DESC LIMIT 100`;return json({items:rows.map((r:any)=>({...r,id:Number(r.id),user_id:r.user_id?Number(r.user_id):null,generation_id:r.generation_id?Number(r.generation_id):null}))});}
 if(route==='settings'){return json({session_user:user.id,timezone:'Africa/Lagos',debug:false,storage:'Vercel Blob + Postgres',provider:'Decart'});}
 return json({error:'Unknown API route'},404);
 }catch(e:any){return json({error:e?.message||'Server error'},400);}}

export async function POST(req:NextRequest,{params}:{params:Promise<{route:string}>}){try{await ensureSchema();await guard(req);const {route}=await params;const user=await getUser();const s=db();
 if(route==='upload'){const fd=await req.formData();const file=fd.get('file');if(!(file instanceof File))throw new Error('Upload failed');const kind=formValue(fd,'kind')||'creative';const mime=file.type;const isVideo=mime.startsWith('video/');const allowed=isVideo?LIMITS.allowed_videos:LIMITS.allowed_images;const max=isVideo?LIMITS.max_video_bytes:LIMITS.max_image_bytes;if(!allowed.includes(mime)||file.size<=0)throw new Error('Unsupported or empty file');if(file.size>max)throw new Error('File is too large');const ext=mime==='image/jpeg'?'jpg':mime==='image/png'?'png':mime==='image/webp'?'webp':mime==='video/webm'?'webm':mime==='video/quicktime'?'mov':'mp4';const project=await projectOk(user.id,Number(formValue(fd,'project_id')));const pathname=`uploads/${new Date().toISOString().slice(0,7).replace('-','/')}/${randomUUID()}.${ext}`;await putPrivate(pathname,file,mime);const rows=await s`INSERT INTO assets(user_id,project_id,kind,original_name,path,mime,size_bytes,source,created_at) VALUES(${user.id},${project},${kind},${file.name},${pathname},${mime},${file.size},'upload',${now()}) RETURNING *`;return json({asset:assetOut(rows[0])});}
 if(route==='projects'){const data=await req.json();const name=String(data.name||'').trim();const description=String(data.description||'').trim();if(!name)throw new Error('Project name is required.');const rows=await s`INSERT INTO projects(user_id,name,description,created_at,updated_at) VALUES(${user.id},${name},${description},${now()},${now()}) RETURNING *`;return json({item:{...rows[0],id:Number(rows[0].id)}});}
 if(route==='project-delete'){const fd=await req.formData();const id=Number(formValue(fd,'id'));const ok=await projectOk(user.id,id);if(!ok)throw new Error('Project not found.');await s`UPDATE generations SET project_id=NULL WHERE project_id=${id} AND user_id=${user.id}`;await s`UPDATE assets SET project_id=NULL WHERE project_id=${id} AND user_id=${user.id}`;await s`DELETE FROM projects WHERE id=${id} AND user_id=${user.id}`;return json({ok:true});}
 if(route==='asset-delete'){const fd=await req.formData();const a=await asset(user.id,Number(formValue(fd,'id')));await deletePrivate(a.path);await s`DELETE FROM assets WHERE id=${a.id} AND user_id=${user.id}`;return json({ok:true});}
 if(route==='history-delete'){const fd=await req.formData();const id=Number(formValue(fd,'id'));await s`DELETE FROM generations WHERE id=${id} AND user_id=${user.id}`;return json({ok:true});}
 if(route==='prompts'){const data=await req.json();const title=String(data.title||'').trim(),body=String(data.body||'').trim(),workspace=data.workspace?String(data.workspace):null;if(!title||!body)throw new Error('Prompt title and body are required');const id=Number(data.id||0);if(id){const rows=await s`UPDATE prompts SET title=${title},body=${body},workspace=${workspace},updated_at=${now()} WHERE id=${id} AND user_id=${user.id} RETURNING *`;return json({item:{...rows[0],id:Number(rows[0].id)}});}const rows=await s`INSERT INTO prompts(user_id,title,body,workspace,created_at,updated_at) VALUES(${user.id},${title},${body},${workspace},${now()},${now()}) RETURNING *`;return json({item:{...rows[0],id:Number(rows[0].id)}});}
 if(route==='prompt-delete'){const fd=await req.formData();await s`DELETE FROM prompts WHERE id=${Number(formValue(fd,'id'))} AND user_id=${user.id}`;return json({ok:true});}
 if(route==='notifications-read'){await s`UPDATE notifications SET read_at=${now()} WHERE user_id=${user.id} AND read_at IS NULL`;return json({ok:true});}
 if(route==='realtime-token'){const origin=process.env.DECART_ORIGIN||req.headers.get('origin')||new URL(req.url).origin;const token=await decart.clientToken(origin);const rows=await s`INSERT INTO realtime_sessions(user_id,workspace,model,status,started_at,metadata_json,created_at) VALUES(${user.id},'realtime',${decart.models.realtime},'connecting',${now()},${JSON.stringify({origin})}::jsonb,${now()}) RETURNING id`;return json({token,model:decart.models.realtime,session_id:Number(rows[0].id)});}
 if(route==='realtime-event'){const data=await req.json();const status=String(data.status||'idle');await s`UPDATE realtime_sessions SET status=${status},error_message=${data.error?String(data.error):null},ended_at=${['disconnected','error'].includes(status)?now():null WHERE id=${Number(data.session_id||0)} AND user_id=${user.id}`;return json({ok:true});}
 if(route==='generate'){const fd=await req.formData();const workspace=formValue(fd,'workspace');const prompt=formValue(fd,'prompt').trim();const inputId=Number(formValue(fd,'input_asset_id'));const refId=Number(formValue(fd,'reference_asset_id'));const project=await projectOk(user.id,Number(formValue(fd,'project_id')));if(!['image','video','vton','restyle'].includes(workspace))throw new Error('Unsupported workspace');const active=await s`SELECT id FROM generations WHERE user_id=${user.id} AND workspace=${workspace} AND status IN ('queued','processing') LIMIT 1`;if(active.length)throw new Error('This workspace already has a generation running. Please wait for it to finish.');if(!inputId)throw new Error('Input file is required');const input=await asset(user.id,inputId);const ref=refId?await asset(user.id,refId):null;const model=(decart.models as any)[workspace];if(workspace==='image' && (!String(input.mime).startsWith('image/')||!prompt))throw new Error('Image Edit requires an image input and prompt.');if(workspace!=='image' && !String(input.mime).startsWith('video/'))throw new Error(`${workspace.toUpperCase()} requires a video input.`);if(['video','vton','restyle'].includes(workspace)&&!prompt&&!ref)throw new Error('Add a prompt or reference image.');const genRows=await s`INSERT INTO generations(user_id,project_id,workspace,model,prompt,status,input_asset_ids,started_at,created_at,metadata_json) VALUES(${user.id},${project},${workspace},${model},${prompt},'processing',${JSON.stringify([inputId,...(ref?[refId]:[])] )}::jsonb,${now()},${now()},${JSON.stringify({workspace,progress:5})}::jsonb) RETURNING *`;const genId=Number(genRows[0].id);await notify(user.id,'started','Generation started',`${workspace} generation is now processing.`,genId);
 try{const ir=await readPrivate(input.path);if(!ir||ir.statusCode!==200)throw new Error('Unable to read input asset');const inputBlob=await new Response(ir.stream).blob();let refBlob:Blob|undefined; if(ref){const rr=await readPrivate(ref.path);if(!rr||rr.statusCode!==200)throw new Error('Unable to read reference asset');refBlob=await new Response(rr.stream).blob();}
 if(workspace==='image'){const rr=await decart.generateImage(model,inputBlob,input.original_name,input.mime,prompt,refBlob,ref?.original_name,ref?.mime,String(formValue(fd,'resolution')||'720p'));const ct=rr.headers.get('content-type')||'image/png';const ext=ct.includes('jpeg')?'jpg':ct.includes('webp')?'webp':'png';const pathname=`generated/${new Date().toISOString().slice(0,7).replace('-','/')}/${randomUUID()}.${ext}`;const outBlob=await rr.blob();await putPrivate(pathname,outBlob,ct);const ins=await s`INSERT INTO assets(user_id,project_id,kind,original_name,path,mime,size_bytes,source,created_at) VALUES(${user.id},${project},'generated',${`generated-${genId}.${ext}`},${pathname},${ct},${outBlob.size},'generated',${now()}) RETURNING *`;const outId=Number(ins[0].id);await s`UPDATE generations SET status='completed',output_asset_id=${outId},metadata_json='{"progress":100}'::jsonb,completed_at=${now()} WHERE id=${genId}`;await notify(user.id,'success','Generation completed','Your image result is ready.',genId);return json({generation:genOut((await s`SELECT * FROM generations WHERE id=${genId}`)[0]),output:assetOut(ins[0])});}
 const job=await decart.submitVideo(model,inputBlob,input.original_name,input.mime,prompt,refBlob,ref?.original_name,ref?.mime);const jobId=String(job.job_id||job.id||'');if(!jobId)throw new Error('Decart did not return a job id');await s`UPDATE generations SET provider_job_id=${jobId},metadata_json=${JSON.stringify({progress:10,provider:job})}::jsonb WHERE id=${genId}`;return json({generation:genOut((await s`SELECT * FROM generations WHERE id=${genId}`)[0]),provider:job});
 }catch(e:any){await s`UPDATE generations SET status='failed',error_message=${e?.message||'Generation failed'},completed_at=${now()} WHERE id=${genId}`;await notify(user.id,'error','Generation failed',e?.message||'Generation failed',genId);throw e;}}
 return json({error:'Unknown API route'},404);
 }catch(e:any){return json({error:e?.message||'Server error'},400);}}
